/* TODO: This file should be autogenerated; find it a better place */

#ifndef _JAILHOUSE_CONFIG_H
#define _JAILHOUSE_CONFIG_H

/* #define ENABLE_VMX */
#define ENABLE_SVM

#if (defined(ENABLE_VMX) && defined(ENABLE_SVM)) || (!defined(ENABLE_VMX) && !defined(ENABLE_SVM))
#error "Either VT-x or AMD-V support must be enabled"
#endif

#endif
